# Generated by Django 5.0.6 on 2024-06-18 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descripttion',
            new_name='description',
        ),
    ]
